version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://user:password@db/app_db
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8000:8000"  # Apenas se precisar acessar o backend diretamente do host para teste

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "80:80"  # Expor apenas o frontend

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
